version: "3"
services:
  transaction-seed:
    container_name: transactions-seed
    build:
      context: ./transactions-seed-app
    environment:
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    depends_on:
      - rabbitmq

  transaction-movements-async-receiver:
    container_name: transaction-movements-async-receiver
    build:
      context: ./transactions-movements-app
      dockerfile: Dockerfile.AsyncReceiver
    environment:
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    depends_on:
      - rabbitmq
      - db

  transaction-movements-api:
    container_name: transaction-movements-api
    build:
      context: ./transactions-movements-app
      dockerfile: Dockerfile.Api
    environment:
      DOTNET_ENVIRONMENT: "Production"
    ports:
      - 9000:80
    restart: always
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    container_name: rabbitMQ
    image: rabbitmq:3.11.10-management
    ports:
      - 5020:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123Abc!@#"

  db:
    container_name: db
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "xpto"
      POSTGRES_PASSWORD: "123Abc!@#"    
      POSTGRES_DB: "TransactionsDb"
