version: "3"
services:
  transaction-seed:
    container_name: transactions-seed
    build:
      context: ./transactions-seed-app
    volumes:
      - ./logs/:/logs
    environment:
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    depends_on:
      - rabbitmq

  transaction-movements-async-receiver:
    container_name: transaction-movements-async-receiver
    build:
      context: ./transactions-movements-app
      dockerfile: Dockerfile.AsyncReceiver
    volumes:
      - ./logs/:/logs
    environment:
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    depends_on:
      - rabbitmq
      - db

  transaction-movements-api:
    container_name: transaction-movements-api
    build:
      context: ./transactions-movements-app
      dockerfile: Dockerfile.Api
    volumes:
      - ./logs/:/logs
    environment:
      DOTNET_ENVIRONMENT: "Production"
    ports:
      - 9000:80
    restart: always
    depends_on:
      - rabbitmq
      - db

  rabbitmq:
    container_name: rabbitMQ
    image: rabbitmq:3.11.10-management
    ports:
      - 5020:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123Abc!@#"

  db:
    container_name: db
    image: postgres:15.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "xpto"
      POSTGRES_PASSWORD: "123Abc!@#"
      POSTGRES_DB: "TransactionsDb"

  # Log collector
  fluentd:
    container_name: fluentd
    build:
      context: ./fluentd
    image: fluentd
    volumes:
      - ./fluentd:/fluentd/etc
      - ./logs/:/fluentd/logs
    depends_on:
      - transaction-seed
      - transaction-movements-async-receiver
      - transaction-movements-api

  elasticsearch:
    image: elasticsearch:8.0.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms2g -Xmx2g"
      xpack.security.enabled: "false"
    depends_on:
      - fluentd

  kibana:
    image: kibana:8.0.0
    container_name: kibana
    ports:
      - "9001:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch