version: "3"
services:
  transaction-seed:
    container_name: transactions-seed
    build:
      context: ./transactions-seed-app
    environment:
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    depends_on:
      - rabbitmq

  transaction-movements-async-receiver:
    container_name: transaction-movements-async-receiver
    build:
      context: ./transactions-movements-app
      dockerfile: Dockerfile.AsyncReceiver
    environment:
      DOTNET_ENVIRONMENT: "Production"
    restart: always
    depends_on:
      - rabbitmq
      - sqlserver

  rabbitmq:
    container_name: rabbitMQ
    image: rabbitmq:3.11.10-management
    ports:
      - 5020:15672
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "123Abc!@#"

  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "123Abc!@#"
